name: .NET 8 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '8.0.x'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ./GithubActionDemo/GithubActionDemo.csproj

    - name: Build
      run: dotnet build ./GithubActionDemo/GithubActionDemo.csproj --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test ./GithubActionDemo/GithubActionDemo.csproj --no-build --verbosity normal
